apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:
  restartPolicy: Never
  containers:
    - name: hello
      image: "ubuntu:14.04"
      tty: true
      # command: ["/bin/echo", "hello", "world"]
      env:
        - name: MESSAGE
          value: "hello world"