apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      nodeSelector: 
       cw-node: common
      containers:
      - name: mongodb
        image: mongo:3.5
        ports:
        - containerPort: 27017
          hostPort: 27017
        env:
        - name: GPG_KEYS
          value: "2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5"
        - name: MONGO_MAJOR
          value: "3.5"
        - name: MONGO_PACKAGE
          value: "mongodb-org-unstable"